# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('created_at', models.DateTimeField(blank=True, default=None, help_text='DateTime this model instance was created.', null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='DateTime this model instance was last updated.')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='1A', help_text='Name of classroom.', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('created_at', models.DateTimeField(blank=True, default=None, help_text='DateTime this model instance was created.', null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='DateTime this model instance was last updated.')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='Example', help_text='Name of school.', max_length=255, null=True, unique=True)),
                ('address', models.TextField(blank=True, default=None, help_text='Address of the school.', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('created_at', models.DateTimeField(blank=True, default=None, help_text='DateTime this model instance was created.', null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='DateTime this model instance was last updated.')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstname', models.CharField(default='', help_text="The student's first name", max_length=30, verbose_name='First Name')),
                ('middlenames', models.CharField(blank=True, default=None, help_text="The student's middle names (space separated, if multiple)", max_length=30, null=True, verbose_name='Middle Names')),
                ('lastname', models.CharField(default='', help_text="The student's last name", max_length=30, verbose_name='Last Name')),
                ('is_active', models.BooleanField(default=True, help_text='True if student has not graduated, left, or been expelled.')),
                ('is_suspended', models.BooleanField(default=False, help_text='True if student is currently on suspension.')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='incling.Classroom')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='incling.School'),
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together=set([('school', 'name')]),
        ),
    ]
